#!groovy

// Generated by IBM TransformationAdvisor
// Mon Oct 29 16:16:35 UTC 2018

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'jpetstoreapp'
    mvnCommands = '--version'
    test='false'
}