# Generated by IBM TransformationAdvisor
# Mon Oct 29 16:16:35 UTC 2018

{{/* vim: set filetype=mustache: */}}
{{/*
Expand the name of the chart.
*/}}
{{- define "jpetstoreapp.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 53 | trimSuffix "-" -}}
{{- end -}}

{{/*
Create a default fully qualified app name.
We truncate at 53 chars because some Kubernetes name fields are limited to 63 (by the DNS naming spec). Allow 10 chars for -service (and such) postfix.
*/}}
{{- define "fullname" -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- printf "%s-%s" .Release.Name $name | trunc 53 | trimSuffix "-" -}}
{{- end -}}

{{/*
Create a default fully qualified app name.
We truncate at 53 chars because some Kubernetes name fields are limited to 63 (by the DNS naming spec). Allow 10 chars for -service (and such) postfix.
*/}}
{{- define "k8name" -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- printf "%s_%s" .Release.Name $name | trunc 53 | trimSuffix "-" | replace "-" "_" | upper -}}
{{- end -}}

{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "jpetstoreapp.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}
{{- end -}}
