apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ template "jpetstoreapp.name" . }}-jpetstoreweb"
  labels:
    app: "{{ template "jpetstoreapp.name" . }}-jpetstoreweb"
    chart: {{ template "jpetstoreapp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            backend:
              serviceName: web
              servicePort: 80
  {{- end }}
